config/routes.rb
KendoGva::Application.routes.draw do

  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users

  root "pages#home"
  get "home", to: "pages#home", as: "home"
  # get "inside", to: "pages#inside", as: "inside"
  # get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"

  resources :posts, only: [:index, :show]

  get "/robots.txt" => RobotsGenerator
  ActiveAdmin.routes(self)

  # namespace :admin do
  #   root "base#index"
  #   resources :users
  #   get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
  #   get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
  #   resources :posts
  # end

end

app/models/post.rb
class Post < ActiveRecord::Base
  # Use friendly_id
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Markdown
  before_save { Markdown.update_html(self) }

  # Validations
  validates :title, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :content_md, presence: true

  # Pagination
  paginates_per 30

  # Relations
  belongs_to :user

  # Scopes
  scope :published, lambda {
    where(draft: false)
    .order("updated_at DESC")
  }

  scope :drafted, lambda {
    where(draft: true)
    .order("updated_at DESC")
  }

end

app/models/startdate.rb
class Startdate < ActiveRecord::Base
  validates_presence_of :start_on
  validates_uniqueness_of :start_on


  def self.future
    where "startdates.start_on >= ?", Date.current
  end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base

  mount_uploader :portrait, PortraitUploader

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :grade
  validates_inclusion_of :grade, in: (1..8).to_a

  def self.active
    where active: true
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Relations
  has_many :posts, dependent: :nullify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Pagination
  paginates_per 100

  # Validations
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def self.paged(page_number)
    order(admin: :desc, email: :asc).page page_number
  end

  def self.search_and_order(search, page_number)
    if search
      where("email LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, email: :asc
      ).page page_number
    else
      order(admin: :desc, email: :asc).page page_number
    end
  end

  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","email","created_at")
  end

  def self.last_signins(count)
    order(last_sign_in_at:
    :desc).limit(count).select("id","email","last_sign_in_at")
  end

  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :reject_locked!, if: :devise_controller?


  # Devise permitted params
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :email,
      :password,
      :password_confirmation
    ])
    devise_parameter_sanitizer.permit(:account_update, keys: [
      :email,
      :password,
      :password_confirmation,
      :current_password
    ])
  end

  # Redirects on successful sign in
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  # Auto-sign out locked users
  def reject_locked!
    if current_user && current_user.locked?
      sign_out current_user
      user_session = nil
      current_user = nil
      flash[:alert] = "Your account is locked."
      flash[:notice] = nil
      redirect_to root_url
    end
  end
  helper_method :reject_locked!

  # Only permits admin users
  def require_admin!
    authenticate_user!

    if current_user && !current_user.admin?
      redirect_to root_path
    end
  end
  helper_method :require_admin!

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [
    :inside
  ]

  def home
    @last_post = Post.order(:created_at).last
    @teachers = Teacher.active.order("grade DESC, name ASC")
    @startdate = Startdate.future.order(:start_on).first
    teachers_size = @teachers.count
    if 12.modulo(teachers_size) == 0
      @teacher_col_width = 12/teachers_size
    else
      @teacher_col_width = 2
    end
  end

  def inside
  end

  def posts
    @posts = Post.published.page(params[:page]).per(10)
  end

  def show_post
    @post = Post.friendly.find(params[:id])
  rescue
    redirect_to root_path
  end


  def email
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]

    if @name.blank?
      flash[:alert] = "Please enter your name before sending your message. Thank you."
      render :contact
    elsif @email.blank? || @email.scan(/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i).size < 1
      flash[:alert] = "You must provide a valid email address before sending your message. Thank you."
      render :contact
    elsif @message.blank? || @message.length < 10
      flash[:alert] = "Your message is empty. Requires at least 10 characters. Nothing to send."
      render :contact
    elsif @message.scan(/<a href=/).size > 0 || @message.scan(/\[url=/).size > 0 || @message.scan(/\[link=/).size > 0 || @message.scan(/http:\/\//).size > 0
      flash[:alert] = "You can't send links. Thank you for your understanding."
      render :contact
    elsif verify_recaptcha(model: @message, action: "email", minimum_score: 0.5)
      ContactMailer.contact_message(@name, @email, @message).deliver
      redirect_to root_path, notice: "Your message was sent. Thank you."
    else
      @last_post = Post.order(:created_at).last
      @teachers = Teacher.active.order("grade DESC, name ASC")
      @startdate = Startdate.future.order(:start_on).first
      teachers_size = @teachers.count
      if 12.modulo(teachers_size) == 0
        @teacher_col_width = 12/teachers_size
      else
        @teacher_col_width = 2
      end
      render :home
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published.page(params[:page]).per(10)
  end

  def show
    @post = Post.friendly.find(params[:id])
  rescue
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | KendoGva"
    end
  end

  def startdate_helper(startdate)
    if startdate
      "La prochaine aura lieu le <strong>#{l startdate.start_on, format: :long}</strong>.".html_safe
    else
      "Il n'y a pour l'instant pas de date prévue pour la prochaine rentrée."
    end
  end
end

app/helpers/email_helper.rb
module EmailHelper
  def line_break(s)
    s.gsub("\n", "<br/>") 
  end
end

app/views/layouts/_divider.html.haml
.row
  .col-sm-12
    %hr.divider

app/views/layouts/_footer.html.haml
#footer
  .container
    .row.footer-first-row
      .col-md-12.text-center
        %p
          %small
            &copy;
            = Date.current.year
            –
            Shung Do Kwan Budo
        %ul.list-inline#social
          %li
            = link_to "<i class='fa fa-twitter'></i> Twitter".html_safe, "https://twitter.com/kendo_in_geneva", id: 'twitter_icon'
          %li
            = link_to "<i class='fa fa-facebook'></i> Facebook".html_safe, "https://www.facebook.com/kendogeneve", id: 'facebook_icon'
          %li
            = link_to "<i class='fa fa-flickr'></i> Flickr".html_safe, "https://www.flickr.com/photos/8469782@N03", id: 'flickr_icon'

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.haml
- if request[:controller] != "pages"
  %nav.navbar.navbar-fixed-top
    .container
      .row
        .col-md-12
          .navbar-header
            %button.navbar-toggle{type: "button", data: {toggle: "collapse", target: "#navigationbar"}}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to image_tag("logo_40_orange.png", size: "40x40", alt: "Logo"), root_path, class: 'navbar-brand'
          #navigationbar.collapse.navbar-collapse.masthead-nav
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to "Home".html_safe, root_path, data: {toggle: "tooltip", placement: "bottom"}, title: "Tous les détails concernant notre club"
              %li
                = link_to "News", posts_path, data: {toggle: "tooltip", placement: "bottom"}, title: "Les dernières nouvelles"
- else
  %nav.navbar.navbar-fixed-top
    .container.visible-xs.visible-sm.hidden-md.hidden-lg
      .row
        .col-md-12
          .navbar-header
            %button.navbar-toggle{type: "button", data: {toggle: "collapse", target: "#navigationbar"}}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to image_tag("logo_40_orange.png", size: "40x40", alt: "Logo"), root_path, class: 'navbar-brand'
          #navigationbar.collapse.navbar-collapse.masthead-nav
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to "Bienvenue", "#bienvenue"
              %li
                = link_to "Dernière nouvelle", "#last_news"
              %li
                = link_to "Horaires", "#horaires"
              %li
                = link_to "Situation", "#location"
              %li
                = link_to "Débuter", "#debuter"
              %li
                = link_to "Cotisations", "#fees"
              %li
                = link_to "Enfants", "#kids"
              %li
                = link_to "Contact", "#contact"
              %li
                = link_to "Newsletter", "#newsletter"
              %li
                = link_to "Calendrier", "#calendrier"
              %li
                = link_to "Kendo", "#kendo"
              %li
                = link_to "Enseignants", "#teachers"
              %li.small
                = link_to "<em>top</em>".html_safe, "#bienvenue"

app/views/layouts/_navigation_links.html.haml
- if request[:controller] != "pages"
  %li
    = link_to "Home".html_safe, root_path, data: {toggle: "tooltip", placement: "bottom"}, title: "Tous les détails concernant notre club"
  %li
    = link_to "News", posts_path, data: {toggle: "tooltip", placement: "bottom"}, title: "Les dernières nouvelles"
- else
  %li
    = link_to "Bienvenue", "#bienvenue"
  %li
    = link_to "Dernière nouvelle", "#last_news"
  %li
    = link_to "Horaires", "#horaires"
  %li
    = link_to "Situation", "#location"
  %li
    = link_to "Débuter", "#debuter"
  %li
    = link_to "Cotisations", "#fees"
  %li
    = link_to "Enfants", "#kids"
  %li
    = link_to "Contact", "#contact"
  %li
    = link_to "Newsletter", "#newsletter"
  %li
    = link_to "Calendrier", "#calendrier"
  %li
    = link_to "Kendo", "#kendo"
  %li
    = link_to "Enseignants", "#teachers"
  %li.small
    = link_to "<em>top</em>".html_safe, "#bienvenue"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    %title= @title || "www.kendo-geneve.ch"
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png'
    = favicon_link_tag 'touch-icon-iphone.png', rel: 'apple-touch-icon', type: 'image/png'
    = favicon_link_tag 'touch-icon-ipad.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "76x76"
    = favicon_link_tag 'touch-icon-iphone-retina.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "120x120"
    = favicon_link_tag 'touch-icon-ipad-retina.png', rel: 'apple-touch-icon', type: 'image/png', sizes: "152x152"
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag "//cdn-images.mailchimp.com/embedcode/classic-081711.css"
    = javascript_include_tag "//use.typekit.net/#{ENV['TYPEKIT_API_KEY']}.js"
    :javascript
      try{Typekit.load();}catch(e){}
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body{class: (request[:controller] != "pages" ? "with_nav" : "")}
    - if flash.present?
      .row
        .col-sm-12.col-md-6.col-md-offset-3.text-center
          = render 'layouts/messages'
    = render "layouts/navigation"
    = yield
    = render 'layouts/footer'
  - if Rails.env.production?
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', '#{ ENV['GOOGLE_ANALYTICS'] }', 'auto');
      ga('send', 'pageview');

app/views/pages/contact.html.erb
<% title("Contact") %>
<div class="container">
  <div class="row">
    <div class="col-sm-6 ">
      <h1 class="page-title">Contact</h1>
      <%= form_tag email_confirmation_path, method: 'post', html: {role: "form"} do %>
        <%= recaptcha_v3(action: "email") %>
        <div class="form-group">
          <%= label_tag :name, "Your name" %>
          <div class="row">
            <div class="col-xs-12">
              <%= text_field_tag :name, @name, placeholder: "Enter your name...", :autofocus => true, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= label_tag :email, "Your email" %>
          <div class="row">
            <div class="col-xs-12">
              <%= text_field_tag :email, @email, placeholder: "Enter your email...", class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= label_tag :message, "Your message" %>
          <div class="row">
            <div class="col-xs-12">
              <%= text_area_tag :message, @message, placeholder: "Enter your message...", rows: 10, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 padded">
            <button class='btn btn-primary'>
              <i class='fa fa-envelope'></i> Send
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.haml
#bienvenue
  .container.jumbotron
    .row
      .col-md-3.hidden-xs.hidden-sm
        #logo
          Kendo GVA
      .col-xs-12.col-sm-12.col-md-9
        %h2
          Bienvenue
        %p
          Nous pratiquons
          = link_to "le Kendo", "#kendo"
          à Genève, en Suisse.
        %p
          =raw "Nous faisons partie du #{link_to "Shung Do Kwan", "http://sdkbudo.ch", target: "_blank"}, un club qui regroupe les pratiquants de divers arts martiaux japonais."
        %p.small
          =raw "Nous sommes membres de la Fédération Suisse de Kendo, elle même affiliée à la #{link_to "Fédération Européenne de Kendo", "http://www.ekf-eu.com/", target: "_blank"} et à la #{link_to "Fédération Internationale de Kendo", "https://www.kendo-fik.org", target: "_blank"}."
        %p.small
          Nous proposons des cours pour débutants et avancés, adultes et enfants.
        %p.small
          =raw "Chaque année au mois de septembre, nous organisons aussi un grand tournoi international: #{link_to "La Coupe Kasahara", "http://kasaharacup.com", target: "_blank", title: "Kasahara Kendo Cup"}."
.container
  .row
    .col-md-9
      - if @last_post
        %section#last_news.panel.panel-default
          .panel-heading
            %h2 Dernière nouvelle
          .panel-body
            = render @last_post
          .panel-footer.text-right
            = link_to "Toutes les nouvelles", posts_path
      %section#horaires
        %h2 Horaires
        .row
          .col-md-6
            %h3 Adultes
            %dl
              %dt Lundi
              %dd 18h30-20h15 (tous niveaux)
              %dt Jeudi
              %dd 18h30-20h00 (débutants)
              %dd 20h00-21h30 (avancés)
          .col-md-6
            %h3 Enfants (dès 8 ans)
            %dl
              %dt Jeudi
              %dd 18h30-19h30
      %section#location
        %h2 Situation
        %p
          Notre Dojo est situé dans la salle de gym de l'école primaire de Cayla à l'adresse suivante:
          %address
            12 rue William-Lescaze
            %br 1203 Genève
          Arrêts TPG “Jean-Jacques” ou “Contrat-Social”
        %iframe#googlemap{src: "https://www.google.com/maps/d/u/0/embed?mid=1xKfb0mA41hccF36sntdqdsMhU9g"}
      %section#debuter
        %h2 Vous voulez nous rejoindre?
        %p
          Nous organisons deux rentrées pour les débutants, au mois de septembre et janvier.
        %p
          = startdate_helper(@startdate)
        %p
          Si vous désirez nous rejoindre, envoyez-nous <a href="#contact">un message</a> pour nous avertir que vous comptez participer à la prochaine rentrée. Ceci facilitera notre organisation.
        %p
          Le jour de la rentrée rejoignez-nous au cours avec une tenue de type “training” ou kimono de judo/karate (si vous en possèdez déjà un). Merci d'être prêt environ 10 minutes avant le début du cours.
        %p
          Si vous ne connaissez pas le kendo, nous vous recommandons de venir assister à une leçon. Le lundi soir, la leçon est mixte (débutants/avancés) et donne donc un très bon aperçu du kendo et de la façon dont il est enseigné dans notre club. N’hésitez pas à nous <a href="#contact">contacter</a> si vous avez des questions.
        %p
          Si vous <strong>pratiquez déjà le kendo</strong>, vous pouvez évidemment rejoindre nos entraînements à tous moments.

      %section#fees
        %h2
          Cotisations annuelles
        %table.table
          %tbody
            %tr
              %th
                Enfants jusqu'à 13 ans
              %td
                390 CHF
            %tr
              %th
                Dès le 2e enfant
              %td
                195 CHF (rabais de 50%)
            %tr
              %th
                Juniors dès l'année civile de leurs 14 ans jusqu'à 20 ans et étudiants
              %td
                460 CHF
            %tr
              %th
                Adultes dès l'année civile de leurs 20 ans
              %td
                660 CHF
            %tr
              %th
                Cotisation annuelle à la Fédération Suisse de Kendo
              %td
                80 CHF (100 CHF la première année)
        %p
          =raw "Vous trouverez plus d'infos sur nos modalités d'inscription et sur nos statuts sur le site du #{link_to "Shung Do Kwan", "http://sdkbudo.ch/index.php/en/sinscrire", target: "_blank"}."
      %section#kids
        %h2
          Cours enfants
        %p
          =raw "Nous proposons des cours aux enfants <strong>dès 8 ans</strong>. Les rentrées pour ces cours se font deux fois par ans, au mois de septembre et janvier."
        %p
          = startdate_helper(@startdate)
        %p
          La Fédération Japonaise définit le Kendo comme un art martial
          %blockquote
            conçu pour discipliner le caractère de l'homme à travers la mise en oeuvre des principes du sabre. Le but de la pratique du Kendo est de former l'esprit et le corps, de cultiver un caractère vigoureux, et, par un entraînement correct et rigoureux, de s'efforcer de progresser dans l'art du Kendo, de tenir en estime la courtoisie et l'honneur, de coopérer avec les autres en toute sincérité, et de toujours poursuivre la culture de soi.
          Dans notre enseignement aux enfants, nous essayons de transmettre au mieux ces valeurs fondamentales.

      %section#contact
        .row
          .col-md-6
            = form_tag email_confirmation_path, method: 'post', html: {role: "form"} do
              = recaptcha_v3(action: "email")
              .panel.panel-default
                .panel-heading
                  %h2 Contactez-nous
                .panel-body

                  .form-group
                    = text_field_tag :name, @name, placeholder: "Nom", class: "form-control"

                  .form-group
                    = text_field_tag :email, @email, placeholder: "Email", class: "form-control"

                  .form-group
                    = text_area_tag :message, @message, placeholder: "Message", rows: 10, class: "form-control"
                  %button.btn.btn-primary
                    %i.fa.fa-envelope
                    Envoyez votre message
          .col-md-6#newsletter
            = form_tag "https://kendo-geneve.us6.list-manage.com/subscribe/post", class: "form" do
              = hidden_field_tag :u, "5545e540aff9e8b07df2f5531"
              = hidden_field_tag :id, "2f8b7857fe"
              .panel.panel-default
                .panel-heading
                  %h2 Newsletter
                .panel-body
                  %p.help-block
                    Inscrivez-vous pour recevoir 1 ou 2 fois par mois des informations concernant nos activités
                  .form-group
                    = text_field_tag 'FNAME', nil, required: true, placeholder: "Prénom", class: "form-control"
                  .form-group
                    = text_field_tag 'LNAME', nil, required: true, placeholder: "Nom", class: "form-control"
                  .form-group
                    = email_field_tag 'EMAIL', nil, required: true, placeholder: "Email", class: "form-control"
                  %button.btn.btn-primary
                    %i.fa.fa-pencil
                    Inscrivez-vous

      %section#calendrier
        %h2 Calendrier
        %iframe#googlecal{src: "https://www.google.com/calendar/embed?showTitle=0&showPrint=0&showTabs=0&showCalendars=0&showTz=0&height=600&wkst=2&hl=fr&bgcolor=%23ffffff&src=o229hp9cnspcv2ua4gt8kipcm8%40group.calendar.google.com&color=%23182C57&src=chocolatepangolin%40gmail.com&color=%23A32929&ctz=Europe%2FZurich", style: " border-width:0 ", frameborder: "0", scrolling: "no"}
      %section#kendo
        %h2 Le Kendo
        %p
          “Le kendo est la plus ancienne, la plus respectée et la plus populaire des disciplines modernes du Budō” remarque en 1983 Donn F. Draeger, l'un des plus grands spécialistes des arts martiaux japonais.
        %p
          Le kendo (littéralement la voie du sabre) est l'évolution moderne du kenjutsu (l'art du sabre). Cet art guerrier, développé par les samouraïs japonais, est représentatif de plusieurs siècles de combats au sabre (katana). Le kendo n'est pas qu'un sport de combat comme l'escrime. Il comprend également tout un volet spirituel (le "Dô", qui signifie la voie). Cet art martial permet à ses pratiquants de développer leur force de caractère et leur détermination.
        %p
          Le kendo peut être pratiqué comme un art martial, mais c'est également un sport de compétition, aujourd'hui largement pratiqué dans le monde.
        %p
          Si vous voulez en savoir plus sur le kendo, n'hésitez pas visiter
          %a{href: "http://fr.wikipedia.org/wiki/Kendo", target: "_blank"}
            la page Wikipedia
          sur le sujet ou à venir nous rencontrer.
      - if @teachers.present?
        %section#teachers.clearfix
          %h2
            Les enseignants
          - @teachers.each do |teacher|
            .teacher{class: "col-sm-#{@teacher_col_width}"}
              - if teacher.portrait.present?
                = image_tag teacher.portrait.url(:medium), class: 'img-circle img-responsive'
              - else
                %i.fa.fa-user
              %h4
                = teacher.name
                %br
                %small
                  = "#{teacher.grade} Dan"

    .col-md-3
      .panel.panel-default#english
        .panel-heading
          %h4
            You don't speak french?
        .panel-body
          %p
          Please note that our classes are given in french but many of our kenshis also speak some english and are ready to give you any information that you may need. Do not hesitate
          = link_to "to contact us", "#contact"
          for any inquiries regarding our activities.


      .sidebar-nav{role: "complementary"}
        %nav.sidenav.hidden-print.hidden-xs.hidden-sm
          %ul.nav
            %li
              = link_to "Bienvenue", "#bienvenue"
            %li
              = link_to "Dernière nouvelle", "#last_news"
            %li
              = link_to "Horaires", "#horaires"
            %li
              = link_to "Situation", "#location"
            %li
              = link_to "Débuter", "#debuter"
            %li
              = link_to "Cotisations", "#fees"
            %li
              = link_to "Enfants", "#kids"
            %li
              = link_to "Contact", "#contact"
            %li
              = link_to "Newsletter", "#newsletter"
            %li
              = link_to "Calendrier", "#calendrier"
            %li
              = link_to "Kendo", "#kendo"
            %li
              = link_to "Enseignants", "#teachers"
            %li.small
              = link_to "<em>top</em>".html_safe, "#bienvenue"

app/views/pages/inside.html.erb
<% title("Protected page") %>
<h1>Protected Page</h1>
<p>This page is only visible to signed in users. Edit it at: <em>views/pages/inside.html.erb</em></p>
<p>You can change the page users see after successfully signing in within the method <em>after_sign_in_path_for</em> inside <strong>application_controller.rb</strong></p>

app/views/pages/posts.html.erb
<% title("Posts") %>
<h1>Posts</h1>

<% @posts.each do |post| %>
	
<div class="title-box">
  <p>
    <%= link_to "#{post.title}", post_path(post.slug) %> <br/>
    <span><small><em><%= time_ago_in_words(post.updated_at) %> ago</em></small></span>
  </p>

</div>
	
<% end %>
	
<div class="pagination-control text-center">
  <%= paginate @posts %> 
</div>

app/views/pages/show_post.html.erb
<% title(@post.title) %>

<div class="row">
  <div class="col-sm-3"><h3><small><i class="fa fa-calendar"></i>&nbsp;&nbsp;<%= @post.updated_at.strftime("%Y, %B %-d") %></small></h3></div>
  <div class="col-sm-9"><%= @post.content_html.html_safe %></div>
</div>

app/views/posts/_post.html.haml
.row.post
  .col-sm-3
    %h3
      = link_to_unless_current post.title, post
      %br
      %small
        %i.fa.fa-calendar
        = post.updated_at.strftime("%Y, %B %-d")
  .col-sm-9
    = post.content_html.html_safe

app/views/posts/index.html.haml
- title("Posts")
.container
  .row
    .col-sm-12
      %h1
  = render partial: @posts, spacer_template: "layouts/divider"
  .row
    .col-sm-12
      .pagination-control.text-center
        = paginate @posts

app/views/posts/show.html.haml
- title @post.title
.container
  .row
    .col-sm-12
      = render @post